#!/bin/bash

cd /home/nicolay/portfolioWebsite
eval $(ssh-agent)
ssh-add ~/.ssh/github
git reset --hard
git pull
composer update
php artisan migrate --force

npm install
npm run build
php artisan view:cache
php artisan route:cache

php artisan test
if [ $? -ne 0 ]; then
        echo exit 1
fi
