#!/bin/bash

cd /home/nicolay/portfolioWebsite
eval $(ssh-agent)
ssh-add ~/.ssh/github
git reset --hard
git pull
composer update
php artisan migrate --force
php artisan test
npm install
npm run build
php artisan view:cache
php artisan route:cache
