services:
    php:
        image: serversideup/php:8.4-fpm-nginx
        volumes:
            - '.:/var/www/html'
        networks:
            - nginx-proxy
        environment:
            VIRTUAL_HOST: nmdammer.com
            LETSENCRYPT_HOST: nmdammer.com
            VIRTUAL_PORT: 8080
            SSL_MODE: "off"
            PHP_OPCACHE_ENABLE: "0"
    redis:
        image: redis
        ports:
            - '9000:9000'
        volumes:
            - redis_data:/data
        networks:
            - nginx-proxy
volumes:
    redis_data:
networks:
    nginx-proxy:
        external: true
